Block explorer 1.1
OnyxPay/onyxchain-explorer-frontend pull request #10
Opened 2019-11-14 15:05 UTC by akorunska

ONXP-1681 [BE] Link to Ontology APIs docs is displayed on mobile browser
ONXP-1659 [BE] Need to fix url for addresses
ONXP-1714 [BE] Links in footer should be updated
ONXP-1684 [BE][GUI] Pagination of transactions lists doesn't work correctly
ONXP-1636 [BE] Missing accounts subtab in test net

2019-11-14 16:14 UTC, arsonaut requested changes

2019-11-14 16:14 UTC, arsonaut commented on src/components/addresses/List.vue
>                lists[i].balance = tmpB.substring(0, tmpB.length - 9) + '.' + tmpB.substring(tmpB.length - 9)
For ONYX, decimals == 8

2019-11-14 16:14 UTC, arsonaut commented on src/components/addresses/List.vue
> +          // };
Remove commented code

2019-11-14 16:14 UTC, arsonaut commented on src/common/lang/en.js
> +    OnyxPay: 'OnyxPay',
For the future, I recommend to add comma after last item — this will prevent one extra diff line ^)

2019-11-14 17:55 UTC, arsonaut approved these changes

2019-11-15 09:08 UTC, filenko45 approved these changes

2019-11-15 09:25 UTC, merged